### ISSUE TITLE
Error for lacking NODE_CLASS_MAPPINGS

### ISSUE THREAD

**Issue by trucaliber** [subtleGradient/TinkerBot-tech-for-ComfyUI-Touchpad#2]
I got the following error during launch.

Skipped TinkerBot-tech-for-ComfyUI-Touchpad module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.

**Comment by SatadalAI** [comment]
Check the below solution: 
https://github.com/subtleGradient/TinkerBot-tech-for-ComfyUI-Touchpad/issues/3#issuecomment-1888354691
