### ISSUE TITLE
(IMPORT FAILED) Touchpad two-finger gesture support for macOS

### ISSUE THREAD

**Issue by guoreex** [subtleGradient/TinkerBot-tech-for-ComfyUI-Touchpad#3]
![image](https://github.com/subtleGradient/TinkerBot-tech-for-ComfyUI-Touchpad/assets/125869801/391e0048-cd10-411f-a0cd-bc051be43c77)
ComfyUI: 1893[b4e915](2024-01-10)
Manager: V1.25.3

Thank you very much for your extension, it is very useful,
There is an error, but it can be used. I don't know what the problem is.

**Comment by SatadalAI** [comment]
Just open the _init_,py file and edit like below:

![image](https://github.com/subtleGradient/TinkerBot-tech-for-ComfyUI-Touchpad/assets/156392125/6edc8fde-756b-41fb-beb1-36de8b9647e6)

**Comment by guoreex** [comment]
@SatadalAI thank u, it's work👍
